### ISSUE TITLE
STAINED_GLASS_PANE errors.

### ISSUE THREAD

**Issue by andrewkm** [lucko/helper#20]
We continue to get the following errors on one of our plugins that uses helper for a /booklet feature we use:

https://pastebin.com/raw/98PgU3Di

The error mentions STAINED_GLASS_PANE however nowhere in our code do we specify STAINED_GLASS_PANE.

Any help would really be appreciated.

bookletgui: https://gist.github.com/andrewkm/224c153de7368059a6ed173f5aff7e0c
commandbooklet: https://gist.github.com/andrewkm/51a8de041c2d13c6da46c97c8038de5a

@jamiesinn

**Comment by lucko** [comment]
Seems like your plugin has been compiled against a different version of helper to the one being used on the server.

That field doesn't exist in the newest version - but perhaps a class you compiled with did reference it.

https://github.com/lucko/helper/blob/master/helper/src/main/java/me/lucko/helper/menu/scheme/StandardSchemeMappings.java#L45-L49

**Comment by MatrixTunnel** [comment]
The reason this is happening is because helper doesn't support 1.13 yet. It's caused by old Material references in `StandardSchemeMappings` if you use GUIs in any way.

I fixed it in my local repo and will make a PR later today :)

**Comment by lucko** [comment]
Solved in:

https://hub.spigotmc.org/jira/browse/SPIGOT-4403

**Comment by andrewkm** [comment]
How is it solved @lucko I'm confused...
We need to use api - 1.13

I'm assuming this is just a matter of waiting on helper to update to 1.13 ?

**Comment by Proximyst** [comment]
Seeing as there is a rather big bug with the compatibility layer (which will not be fixed per what I've been told over IRC), I have to use `api-version: 1.13` - This means this error is still persistent, seeing as that disabled the compatibility layer.

Is there a chance this will be fixed sometime soon nonetheless?
